from dataclasses import dataclass
import struct
import random

ActorList = [
            "Enemy_Assassin_Junior",
            "Enemy_Assassin_Junior_GateKeeper",
            "Enemy_Assassin_Junior_Practice",
            "Enemy_Assassin_Junior_Rider",
            "Enemy_Assassin_Junior_Rider_Bow",
            "Enemy_Assassin_Shooter_Junior",
            "Enemy_Assassin_Shooter_Junior_Practice",
            "Enemy_Bokoblin_Armor_Dark",
            "Enemy_Bokoblin_Armor_Junior",
            "Enemy_Bokoblin_Armor_Middle",
            "Enemy_Bokoblin_Armor_Senior",
            "Enemy_Bokoblin_Bone_Junior",
            "Enemy_Bokoblin_Dark",
            "Enemy_Bokoblin_Guard_Junior",
            "Enemy_Bokoblin_Guard_Junior_Ambush",
            "Enemy_Bokoblin_Guard_Junior_Cliff",
            "Enemy_Bokoblin_Guard_Junior_TreeHouseTop",
            "Enemy_Bokoblin_Guard_Middle",
            "Enemy_Bokoblin_Guard_Middle_Ambush",
            "Enemy_Bokoblin_Guard_Middle_Cliff",
            "Enemy_Bokoblin_Guard_Middle_TreeHouseTop",
            "Enemy_Bokoblin_Middle",
            "Enemy_Bokoblin_Junior",
            "Enemy_Bokoblin_NoSleep_Junior",
            "Enemy_Bokoblin_Senior",
            "Enemy_Bokoblin_Sniper_Junior",
            "Enemy_Chuchu_Electric_Junior",
            "Enemy_Chuchu_Electric_Middle",
            "Enemy_Chuchu_Electric_Middle_Army",
            "Enemy_Chuchu_Electric_Senior",
            "Enemy_Lizalfos_Ice_GerudoCanyon_Popup",
            "Enemy_Chuchu_Fire_Junior",
            "Enemy_Chuchu_Fire_Middle",
            "Enemy_Chuchu_Fire_Middle_Army",
            "Enemy_Chuchu_Fire_Senior",
            "Enemy_Chuchu_Ice_Junior",
            "Enemy_Chuchu_Ice_Middle",
            "Enemy_Chuchu_Ice_Middle_Army",
            "Enemy_Chuchu_Ice_Senior",
            "Enemy_Chuchu_Junior",
            "Enemy_Chuchu_Middle",
            "Enemy_Chuchu_Senior",
            "Enemy_Golem_Little",
            "Enemy_Golem_Little_Ice",
            "Enemy_Golem_Little_Fire",
            "Enemy_Keese",
            "Enemy_Keese_AllDay",
            "Enemy_Keese_Electric",
            "Enemy_Keese_Fire",
            "Enemy_Keese_Fire_AllDay",
            "Enemy_Keese_Electric_AllDay",
            "Enemy_Keese_Ice_Army",
            "Enemy_Lizalfos_Dark",
            "Enemy_Lizalfos_Electric",
            "Enemy_Lizalfos_Fire",
            "Enemy_Lizalfos_Fire_GerudoCanyon",
            "Enemy_Lizalfos_Fire_GerudoCanyon_PopUp",
            "Enemy_Lizalfos_Guard_Junior",
            "Enemy_Lizalfos_Guard_Middle",
            "Enemy_Lizalfos_Guard_Junior_LongVisibility",
            "Enemy_Lizalfos_Guard_Middle_LongVisibility",
            "Enemy_Lizalfos_Ice",
            "Enemy_Lizalfos_Ice_GerudoCanyon",
            "Enemy_Lizalfos_Junior",
            "Enemy_Lizalfos_Middle",
            "Enemy_Lizalfos_Senior",
            "Enemy_Octarock",
            "Enemy_Octarock_Desert",
            "Enemy_Octarock_Forest",
            "Enemy_Octarock_Snow",
            "Enemy_Octarock_Stone",
            "Enemy_Toby_Junior",
            "Enemy_Toby_Junior_Sky",
            "Enemy_Toby_Junior_Terminal",
            "Enemy_Zombie_Junior",
            "Enemy_Lizalfos_Bone_Junior",
            "Enemy_Mogurudo_Baby_Junior",
            "Enemy_Zonau_Golem_Dark",
            "Enemy_Assassin_Middle",
            "Enemy_Bokoblin_Boss_Junior",
            "Enemy_Bokoblin_Boss_Dark",
            "Enemy_Bokoblin_Boss_Middle",
            "Enemy_Bokoblin_Boss_Senior",
            "Enemy_Giant_Junior_KeyCrystal",
            "Enemy_Giant_Senior",
            "Enemy_Horablin_Dark",
            "Enemy_Horablin_Guard_Junior",
            "Enemy_Horablin_Guard_Middle",
            "Enemy_Horablin_Junior",
            "Enemy_Horablin_Middle",
            "Enemy_Horablin_Senior",
            "Enemy_LikeLike_Crack",
            "Enemy_LikeLike_Fire",
            "Enemy_LikeLike_Ice",
            "Enemy_LikeLike_Plane",
            "Enemy_LikeLike_Tar",
            "Enemy_Moriblin_Bone_Junior_AllDay",
            "Enemy_Moriblin_Dark",
            "Enemy_Moriblin_Junior",
            "Enemy_Moriblin_Junior_LongSight",
            "Enemy_Moriblin_Junior_Lookout_Cliff",
            "Enemy_Moriblin_Middle",
            "Enemy_Moriblin_Senior",
            "Enemy_PhantomGanon",
            "Enemy_Wizzrobe_Electric",
            "Enemy_Wizzrobe_Electric_Senior",
            "Enemy_Wizzrobe_Fire",
            "Enemy_Wizzrobe_Fire_Senior",
            "Enemy_Wizzrobe_Ice",
            "Enemy_Wizzrobe_Ice_Senior",
            "Enemy_Zombie_Boss_Junior",
            "Enemy_Zonau_Golem_Dark",
            "Enemy_Zonau_Golem_Junior",
            "Enemy_Zonau_Golem_Middle",
            "Enemy_Zonau_Golem_Senior",
            "Enemy_Zonau_Golem_Junior_ForFirstSmallDungeon",
            "Enemy_Zonau_Robot_Dark",
            "Enemy_Zonau_Robot_Junior",
            "Enemy_Zonau_Robot_Junior_Beginning",
            "Enemy_Zonau_Robot_Junior_Lookout",
            "Enemy_Zonau_Robot_Junior_Lookout_Mile",
            "Enemy_Zonau_Robot_Middle",
            "Enemy_Zonau_Robot_Middle_Lookout",
            "Enemy_Zonau_Robot_Senior",
            "Enemy_Lynel_Dark",
            "Enemy_Lynel_Boss",
            "Enemy_Lynel_Boss_Dark",
            "Enemy_Lynel_Boss_Middle",
            "Enemy_Lynel_Boss_Senior",
            "Enemy_Lynel_Junior",
            "Enemy_Lynel_Middle",
            "Enemy_Lynel_Senior",
            "Enemy_Assassin_Senior",
            "Enemy_Drake_Electric",
            "Enemy_Drake_Fire",
            "Enemy_Drake_Ice",
            "Enemy_Drake_Mix",
            "Enemy_DungeonBoss_Gerudo_Uncleared",
            "Enemy_DungeonBoss_Goron_Uncleared",
            "Enemy_DungeonBoss_Rito_Uncleared",
            "Enemy_DungeonBoss_Zonau",
            "Enemy_DungeonBoss_Zora_Uncleared",
            "Enemy_Ganondorf",
            "Enemy_Ganondorf_Miasma",
            "Enemy_Giant_Bone",
            "Enemy_Golem_Fire",
            "Enemy_Golem_Fort_A",
            "Enemy_Golem_Ice",
            "Enemy_Golem_Junior",
            "Enemy_Golem_Middle",
            "Enemy_Golem_Senior",
            "Enemy_Sandworm",
            "Enemy_Zonau_BlockMaster_Junior",
            "Enemy_Zonau_BlockMaster_Middle",
            "Enemy_Zonau_BlockMaster_Senior",
            "Enemy_Mogurudo_Junior",
            "Enemy_Mogurudo_Middle",
            "Enemy_Mogurudo_Senior"
            ]

@dataclass
class RequestActor:
    packet: int
    amount: int
    actor: str

    async def to_bytes(self):
        return struct.pack('<I', self.packet) + struct.pack('<I', self.amount) + struct.pack(f'!{len(self.actor)}s', self.actor.encode()) + struct.pack('<I', 0)

    @classmethod
    async def from_sentence(cls, sentence_array, packet):

        if sentence_array[1] == "random" or sentence_array[1] == "r":
            instance = cls(packet=packet, amount=1, actor=random.choice(ActorList))
            return await instance.to_bytes()
        elif len(sentence_array) < 2:
            instance = cls(packet=packet, amount=1, actor=sentence_array[1])
            return await instance.to_bytes()
        else:
            instance = cls(packet=packet, amount=int(sentence_array[1]), actor=sentence_array[2])
            return await instance.to_bytes()