name: Build multiplatform

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Windows
          os: windows-latest
          artifactsPath: ./src/dist/*.exe
        - name: Linux
          os: ubuntu-20.04
          artifactsPath: ./src/dist/*.AppImage
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.0"
    - name: Install dependencies Linux
      if: startsWith(matrix.name, 'Linux' )
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller aioconsole
    - name: Install dependencies Windows
      if: startsWith(matrix.name, 'Windows' )
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller aioconsole
    - name: Build ${{ matrix.name }}
      run: |
        cd ./src/
        python ./compile.py
      if: ${{ !endsWith(matrix.name, 'dir') }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-${{ matrix.name }}
        path: ./src/dist
    - name: Publish release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ matrix.artifactsPath }}
        tag: ${{ inputs.tag }}
        name: UltraCam Console ${{ inputs.tag }}
        allowUpdates: true
        artifactErrorsFailBuild: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
